# Generated by Django 4.1.3 on 2022-11-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog'),
        ),
    ]
