# Generated by Django 4.1.3 on 2022-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_comment_comment_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentInstance',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
