# Generated by Django 4.1.3 on 2022-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='email_address',
            field=models.EmailField(default='joeblogs@email.com', max_length=254),
        ),
    ]
