# Generated by Django 4.1.3 on 2022-12-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogger_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='email_address',
        ),
    ]
